// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4rvSlZOwdrnh50aGD-qPxegt_3i6Rq0g',
    appId: '1:314816189952:web:27d3c40bd0a689356eeae5',
    messagingSenderId: '314816189952',
    projectId: 'reminddong',
    authDomain: 'reminddong.firebaseapp.com',
    storageBucket: 'reminddong.firebasestorage.app',
    measurementId: 'G-SGDTQ653J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9n4qSy2M0LDZZe4su2rACPu9yTDSpPNE',
    appId: '1:314816189952:android:67d279c3d1e2db146eeae5',
    messagingSenderId: '314816189952',
    projectId: 'reminddong',
    storageBucket: 'reminddong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlRFiCwXfim2j5FdWP4l3Akmpq8Q0bQIM',
    appId: '1:314816189952:ios:fc50e014ae91d0ae6eeae5',
    messagingSenderId: '314816189952',
    projectId: 'reminddong',
    storageBucket: 'reminddong.firebasestorage.app',
    iosBundleId: 'com.example.reminddongApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlRFiCwXfim2j5FdWP4l3Akmpq8Q0bQIM',
    appId: '1:314816189952:ios:fc50e014ae91d0ae6eeae5',
    messagingSenderId: '314816189952',
    projectId: 'reminddong',
    storageBucket: 'reminddong.firebasestorage.app',
    iosBundleId: 'com.example.reminddongApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4rvSlZOwdrnh50aGD-qPxegt_3i6Rq0g',
    appId: '1:314816189952:web:c9bf038af7546c836eeae5',
    messagingSenderId: '314816189952',
    projectId: 'reminddong',
    authDomain: 'reminddong.firebaseapp.com',
    storageBucket: 'reminddong.firebasestorage.app',
    measurementId: 'G-LQ8408J8ZY',
  );
}
